<table width='100%' border='0'>
    <tr>
        <td><img src='images/ucd.png' width='120'></td>
        <td><img src='images/dept_inf.png' width='350'></td>
        <td><img src='images/fs.png' width='120'></td>
    </tr>
</table>

# Langage Python

Email : <a href='mailto:madani.a@ucd.ac.ma'>madani.a@ucd.ac.ma</a>
<img src='images/python.png'>

# <center>Pratique de Numpy</center>

## Importer les modules nécessaires dans cet exercice

In [2]:
import numpy as np
import random

### Utiliser les méthodes floor, ceil, round et trunc

In [4]:
val = 5.99
print("Floor ",np.floor(val))
print("Ceil ",np.ceil(val))
print("Round ",np.round(val))
print("Trunc ",np.trunc(val))
print("La partie entiere est ", int(val))

Floor  5.0
Ceil  6.0
Round  6.0
Trunc  5.0
La partie entiere est  5


In [23]:
val = np.array([1, 5.6, 7.2, 8.9])
print("val :", val)
print("Floor ",np.floor(val))
print("Ceil ",np.ceil(val))
print("Round ",np.round(val))
print("Trunc ",np.trunc(val))

val : [1.  5.6 7.2 8.9]
Floor  [1. 5. 7. 8.]
Ceil  [1. 6. 8. 9.]
Round  [1. 6. 7. 9.]
Trunc  [1. 5. 7. 8.]


### Tester si aucun élément n’est nul dans un tableau

In [29]:
#Rappels sur all et any de numpy
notes = np.array([9, 0, 15.75, 17.25, 10.5, 9.75])
print("Toutes les notes sont >= à 10 : ",np.all(notes>=10))
print("Il existe au moins une note >= à 10",np.any(notes>=10))

Toutes les notes sont >= à 10 :  False
Il existe au moins une note >= à 10 True


In [33]:
#Réponse à l'exercice
#Tous les éléments sont non nuls
# np.all(condition)
print(np.all(notes==0))
print(np.all(notes))

False
False


### Tester s’il existe au moins un élément nul dans un tableau numpy.

In [34]:
notes = np.array([9, 0, 15.75, 17.25, 10.5, 9.75]) #from scratch
print("Il existe au moins un élément nul ", np.any(notes==0))

Il existe au moins un élément nul  True


### Créer un tableau Numpy d’entiers compris entre 30 et 70.

In [38]:
#Rappels de range
for i in range(3, 10):#3, 4, 5, ..., 9
    print(i)
print("-----------------")
for i in range(3, 10,2):#3, 5, 7, 9
    print(i)
print("--------------")
for i in range(10):#3, 4, 5, ..., 9
    print(i)

3
4
5
6
7
8
9
-----------------
3
5
7
9
--------------
0
1
2
3
4
5
6
7
8
9


In [48]:
tab = np.arange(30,71)
print(tab)
print(np.max(tab))
print(np.min(tab))
print(np.sum(tab))
print(np.mean(tab))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
70
30
2050
50.0


In [49]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


### Créer un tableau NumPy contenant les nombres pairs compris entre 30 et 70.

In [55]:
tab = np.arange(30, 71, 2)
tab

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [58]:
tab = []
for i in range(30, 71):
    if i%2==0:
        tab.append(i)
type(tab)

list

### Créer une matrice identité 3x3

In [69]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Générer un nombre aléatoire compris entre 0 et 1.

In [2]:
#un nombre aléatoire réel entre [0,1[
import random
x = random.random()
print(x)

0.6398623654116842


In [101]:
#un nombre aléatoire réel entre [a, b[
a=5
b=10
x = (b-a)*random.random()+a
print(x)

6.516507710611416


In [107]:
#un nombre aléatoire réel entre [a, b[
x = random.uniform(5, 10)
print(x)

6.661451734671122


In [122]:
#un nombre aléatoire entier entre [a, b]
x = random.randint(5,10)
print(x)

10


In [5]:
#Choisir un élément au hasard à partir d'une liste
liste =['Madani','Souhar','Barakatou','Zouaki']
random.choice(liste)

'Souhar'

In [10]:
np.random.choice(liste)

'Barakatou'

In [139]:
#une matrice 1d de 10 valeurs aléatoires [0,1[
np.random.random(5)

array([0.07511682, 0.67773599, 0.13844739, 0.09518084, 0.9768966 ])

In [153]:
#une matrice 2d de 10 valeurs aléatoires [0,1[
np.random.random((5,3))

array([[0.59054039, 0.67485216, 0.75115092],
       [0.46635278, 0.90948473, 0.7952046 ],
       [0.90090725, 0.81503656, 0.50105467],
       [0.20530458, 0.86508433, 0.7316198 ],
       [0.26888513, 0.89235714, 0.28543553]])

In [163]:
#tableau de 10 valeurs aléatoires entre 1 et 5
np.random.randint(1, 5, 10)

array([4, 1, 4, 1, 3, 3, 4, 3, 2, 2])

In [171]:
#Choir un élément au hasard à partir d'un tableau Numpy
tab = np.arange(0, 21)
np.random.choice(tab)

5

In [178]:
#Choisir plusieurs éléments au hasard à partir d'un tableau Numpy
tab = np.arange(0, 21)
np.random.choice(tab, 6)

array([ 8, 19, 12, 18,  6, 18])

In [12]:
#Choisir un élément au hasard à partir d'un tableau Numpy
tab = np.arange(0, 21)
np.random.choice(tab,(2,3))

array([[17, 18,  8],
       [18, 11, 14]])

### Créer une matrice 3X4 à partir de arange().

In [183]:
tab1 = np.arange(12)
print(tab1)
tab2 = tab1.reshape((3,4))
print(tab2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### Créer un vecteur contenant 7 valeurs uniformémet distribuées entre 5 et 50.

In [187]:
np.linspace(5, 50, 7)

array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ])

### Un vecteur contenant 5 entiers aléatoire entre 0 et 10.

In [195]:
np.random.randint(0,10, 5)

array([2, 0, 5, 9, 1])

### Le nombre de lignes et de colonnes d’une matrice donnée.

In [200]:
tab = np.random.random((5,6))
print("Dimension ",tab.shape)
print("#lignes : ", tab.shape[0])
print("#colonnes : ", tab.shape[1])
print("#éléments : ", tab.size)

Dimension  (5, 6)
#lignes :  5
#colonnes :  6
#éléments :  30


### Une matrice remplie par des zéros sauf la diagonale qui est remplie par les valeurs 1, 2, 3, 4 et 5

In [201]:
np.diag([1, 2, 3, 4 ,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### La somme de tous les élements, la somme de chaque colonne et la somme de chaque ligne.

In [206]:
tab = np.array([[10, 20, 30, 40],[1,2,3,4],[13,14,15, 16]])
print("Matrice:",tab)
print("Somme des éléments de la matrice:",np.sum(tab))
print("Somme des colonnes de la matrice:",np.sum(tab, axis=0))
print("Somme des lignes de la matrice:",np.sum(tab, axis=1))

Matrice: [[10 20 30 40]
 [ 1  2  3  4]
 [13 14 15 16]]
Somme des éléments de la matrice: 168
Somme des colonnes de la matrice: [24 36 48 60]
Somme des lignes de la matrice: [100  10  58]


### La multiplication de deux matrices.

In [214]:
tab1 = np.array([[1,2,3],[10,20,30]])
tab2 = np.array([[1,0,3],[10,0,30]])
tab3 = np.array([[1,2],[10,20],[4,5]])
print("tab1", tab1)
print("tab2",tab2)
print("tab3", tab3)
somme  = tab1+tab2
print("Somme de tab1 et tab2", somme)
print("Produit élément par élément ",tab1*tab2)
print("Produit matricielle ", np.dot(tab1, tab3))

tab1 [[ 1  2  3]
 [10 20 30]]
tab2 [[ 1  0  3]
 [10  0 30]]
tab3 [[ 1  2]
 [10 20]
 [ 4  5]]
Somme de tab1 et tab2 [[ 2  2  6]
 [20 20 60]]
Produit élément par élément  [[  1   0   9]
 [100   0 900]]
Produit matricielle  [[ 33  57]
 [330 570]]


### Le déterminant d’une matrice carrée.

In [216]:
tab1 = np.array([[1,2],[10,20]])
np.linalg.det(tab1)

1.1102230246251546e-15

### La norme d’un vecteur ou d’une matrice.

In [217]:
tab1 = np.array([[1,2,3],[10,20,30]])
np.linalg.norm(tab1)

37.603191353926334

In [219]:
tab3 = np.arange(10,16)
np.linalg.norm(tab3)

30.903074280724887

### L’inverse d’une matrice

In [220]:
tab1 = np.array([[1,2],[10,20]])
np.linalg.inv(tab1)

array([[ 1.80143985e+16, -1.80143985e+15],
       [-9.00719925e+15,  9.00719925e+14]])

### La somme de la diagonale d’une matrice.

In [222]:
tab1 = np.array([[1,2],[10,20]])
print(tab1)
print(np.trace(tab1))

[[ 1  2]
 [10 20]]
21


### La matrice triangulaire inférieur dans la décomposition de Cholesky

In [225]:
tab1 = np.array([[4, 12, -16],[12, 37, -53],[-16,-53,98]])
print(tab1)
Triangulaire = np.linalg.cholesky(tab1)
Triangulaire

[[  4  12 -16]
 [ 12  37 -53]
 [-16 -53  98]]


array([[ 2.,  0.,  0.],
       [ 6.,  1.,  0.],
       [-8., -5.,  3.]])

### La racine des polynomes suivants :

a) x2 − 4x + 7.

b) x4 − 11x3 + 9x2 + 11x – 10


In [229]:
np.roots([1, -4, 7])

array([2.+1.73205081j, 2.-1.73205081j])

In [230]:
np.roots([1, -11, 9, 11, -10])

array([10.+0.0000000e+00j, -1.+0.0000000e+00j,  1.+9.6357437e-09j,
        1.-9.6357437e-09j])